CREATE TABLE cliente (
	id_cliente INT(18) AUTO_INCREMENT,
	id_tipo_cliente INT(18) NOT NULL,
	id_tipo_pessoa INT(18) NOT NULL,	
	data_cadastro DATETIME  NOT NULL,
	tipo_pessoa TINYINT NOT NULL,
	nome VARCHAR(255) NOT NULL,
	razao_social VARCHAR(255),
	cpf_cnpj VARCHAR(18) NOT NULL,
	inscricao VARCHAR(25),
	endereco VARCHAR(255) NOT NULL,
	numero VARCHAR(30) NOT NULL,
	bairro VARCHAR(255) NOT NULL,
	cidade VARCHAR(255) NOT NULL,
	complemento VARCHAR(255),
	cep VARCHAR(9) NOT NULL,
	uf VARCHAR(2) NOT NULL,
	observacoes TEXT,
	CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
	FOREIGN KEY fk_tipo_cliente_cliente (id_tipo_cliente) REFERENCES tipo_cliente(id_tipo_cliente),
	FOREIGN KEY fk_tipo_pessoa_cliente (id_tipo_pessoa) REFERENCES tipo_pessoa(id_tipo_pessoa)
) ENGINE=INNODB;